---
- name: Make sure the VRF does not already exist
  hosts: leaf
  gather_facts: false
  remote_user: "{{remote_user}}"
  connection: local

  tasks:
              - name: Get VRF list
                nxos_command:
                  commands: "show vrf | json"
                register: result

              - name: Save output
                set_fact:
                  vrf: "{{ result.stdout[0].TABLE_vrf.ROW_vrf }}"


              - name: Check if vrf exists
                check_vrf:
                  vrf_list: "{{ vrf }}"
                  vrf_name: "{{ vrf_name }}"
                register: vrf

              - debug:
                  msg: "{{ vrf }}"

              - name: Check if vrf exists
                assert:
                  that: vrf.meta.vrf is match("notexist")
                  fail_msg: "VRF name already exist"
                  success_msg: "VRF name not taken"

              - name: Create VRF
                nxos_vrf:
                  name: "{{ vrf_name }}"              



    