---
- name: TEST
  hosts: ios
  gather_facts: false
  remote_user: "{{remote_user}}"
  connection: local

  tasks:
              - name: TST
                ios_config:
                  commands: "hostname {{hostname}}"
                register: result

              - debug: var=result
